In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [101]:
from sklearn.datasets import load_iris
iris=sns.load_dataset('iris')
iris.head(5)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [102]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [103]:
iris.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [105]:
iris.groupby('species').count()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa                50           50            50           50
versicolor            50           50            50           50
virginica             50           50            50           50

In [30]:
data=np.array(iris.iloc[:,0:4])
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [32]:
data.mean(axis=0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [41]:
np.std(data,axis=0)

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [64]:
def sta(x):
    y=(x-x.mean())/x.std()
    return y

c=np.zeros((4,len(data)))
for i in [0,1,2,3]:
    c[i]=sta(data[:,i])
c

array([[-9.00681170e-01, -1.14301691e+00, -1.38535265e+00,
        -1.50652052e+00, -1.02184904e+00, -5.37177559e-01,
        -1.50652052e+00, -1.02184904e+00, -1.74885626e+00,
        -1.14301691e+00, -5.37177559e-01, -1.26418478e+00,
        -1.26418478e+00, -1.87002413e+00, -5.25060772e-02,
        -1.73673948e-01, -5.37177559e-01, -9.00681170e-01,
        -1.73673948e-01, -9.00681170e-01, -5.37177559e-01,
        -9.00681170e-01, -1.50652052e+00, -9.00681170e-01,
        -1.26418478e+00, -1.02184904e+00, -1.02184904e+00,
        -7.79513300e-01, -7.79513300e-01, -1.38535265e+00,
        -1.26418478e+00, -5.37177559e-01, -7.79513300e-01,
        -4.16009689e-01, -1.14301691e+00, -1.02184904e+00,
        -4.16009689e-01, -1.14301691e+00, -1.74885626e+00,
        -9.00681170e-01, -1.02184904e+00, -1.62768839e+00,
        -1.74885626e+00, -1.02184904e+00, -9.00681170e-01,
        -1.26418478e+00, -9.00681170e-01, -1.50652052e+00,
        -6.58345429e-01, -1.02184904e+00,  1.40150837e+00,
         6.74501145e-01,  1.28034050e+00, -4.16009689e-01,
         7.95669016e-01, -1.73673948e-01,  5.53333275e-01,
        -1.14301691e+00,  9.16836886e-01, -7.79513300e-01,
        -1.02184904e+00,  6.86617933e-02,  1.89829664e-01,
         3.10997534e-01, -2.94841818e-01,  1.03800476e+00,
        -2.94841818e-01, -5.25060772e-02,  4.32165405e-01,
        -2.94841818e-01,  6.86617933e-02,  3.10997534e-01,
         5.53333275e-01,  3.10997534e-01,  6.74501145e-01,
         9.16836886e-01,  1.15917263e+00,  1.03800476e+00,
         1.89829664e-01, -1.73673948e-01, -4.16009689e-01,
        -4.16009689e-01, -5.25060772e-02,  1.89829664e-01,
        -5.37177559e-01,  1.89829664e-01,  1.03800476e+00,
         5.53333275e-01, -2.94841818e-01, -4.16009689e-01,
        -4.16009689e-01,  3.10997534e-01, -5.25060772e-02,
        -1.02184904e+00, -2.94841818e-01, -1.73673948e-01,
        -1.73673948e-01,  4.32165405e-01, -9.00681170e-01,
        -1.73673948e-01,  5.53333275e-01, -5.25060772e-02,
         1.52267624e+00,  5.53333275e-01,  7.95669016e-01,
         2.12851559e+00, -1.14301691e+00,  1.76501198e+00,
         1.03800476e+00,  1.64384411e+00,  7.95669016e-01,
         6.74501145e-01,  1.15917263e+00, -1.73673948e-01,
        -5.25060772e-02,  6.74501145e-01,  7.95669016e-01,
         2.24968346e+00,  2.24968346e+00,  1.89829664e-01,
         1.28034050e+00, -2.94841818e-01,  2.24968346e+00,
         5.53333275e-01,  1.03800476e+00,  1.64384411e+00,
         4.32165405e-01,  3.10997534e-01,  6.74501145e-01,
         1.64384411e+00,  1.88617985e+00,  2.49201920e+00,
         6.74501145e-01,  5.53333275e-01,  3.10997534e-01,
         2.24968346e+00,  5.53333275e-01,  6.74501145e-01,
         1.89829664e-01,  1.28034050e+00,  1.03800476e+00,
         1.28034050e+00, -5.25060772e-02,  1.15917263e+00,
         1.03800476e+00,  1.03800476e+00,  5.53333275e-01,
         7.95669016e-01,  4.32165405e-01,  6.86617933e-02],
       [ 1.01900435e+00, -1.31979479e-01,  3.28414053e-01,
         9.82172869e-02,  1.24920112e+00,  1.93979142e+00,
         7.88807586e-01,  7.88807586e-01, -3.62176246e-01,
         9.82172869e-02,  1.47939788e+00,  7.88807586e-01,
        -1.31979479e-01, -1.31979479e-01,  2.16998818e+00,
         3.09077525e+00,  1.93979142e+00,  1.01900435e+00,
         1.70959465e+00,  1.70959465e+00,  7.88807586e-01,
         1.47939788e+00,  1.24920112e+00,  5.58610819e-01,
         7.88807586e-01, -1.31979479e-01,  7.88807586e-01,
         1.01900435e+00,  7.88807586e-01,  3.28414053e-01,
         9.82172869e-02,  7.88807586e-01,  2.40018495e+00,
         2.63038172e+00,  9.82172869e-02,  3.28414053e-01,
         1.01900435e+00,  1.24920112e+00, -1.31979479e-01,
         7.88807586e-01,  1.01900435e+00, -1.74335684e+00,
         3.28414053e-01,  1.01900435e+00,  1.70959465e+00,
        -1.31979479e-01,  1.70959465e+00,  3.28414053e-01,
         1.47939788e+00,  5.58610819e-01,  3.28414053e-01,
         3.28414053e-01,  9.82172869e-02, -1.74335684e+00,
        -5.92373012e-01, -5.92373012e-01,  5.58610819e-01,
        -1.51316008e+00, -3.62176246e-01, -8.22569778e-01,
        -2.43394714e+00, -1.31979479e-01, -1.97355361e+00,
        -3.62176246e-01, -3.62176246e-01,  9.82172869e-02,
        -1.31979479e-01, -8.22569778e-01, -1.97355361e+00,
        -1.28296331e+00,  3.28414053e-01, -5.92373012e-01,
        -1.28296331e+00, -5.92373012e-01, -3.62176246e-01,
        -1.31979479e-01, -5.92373012e-01, -1.31979479e-01,
        -3.62176246e-01, -1.05276654e+00, -1.51316008e+00,
        -1.51316008e+00, -8.22569778e-01, -8.22569778e-01,
        -1.31979479e-01,  7.88807586e-01,  9.82172869e-02,
        -1.74335684e+00, -1.31979479e-01, -1.28296331e+00,
        -1.05276654e+00, -1.31979479e-01, -1.05276654e+00,
        -1.74335684e+00, -8.22569778e-01, -1.31979479e-01,
        -3.62176246e-01, -3.62176246e-01, -1.28296331e+00,
        -5.92373012e-01,  5.58610819e-01, -8.22569778e-01,
        -1.31979479e-01, -3.62176246e-01, -1.31979479e-01,
        -1.31979479e-01, -1.28296331e+00, -3.62176246e-01,
        -1.28296331e+00,  1.24920112e+00,  3.28414053e-01,
        -8.22569778e-01, -1.31979479e-01, -1.28296331e+00,
        -5.92373012e-01,  3.28414053e-01, -1.31979479e-01,
         1.70959465e+00, -1.05276654e+00, -1.97355361e+00,
         3.28414053e-01, -5.92373012e-01, -5.92373012e-01,
        -8.22569778e-01,  5.58610819e-01,  3.28414053e-01,
        -5.92373012e-01, -1.31979479e-01, -5.92373012e-01,
        -1.31979479e-01, -5.92373012e-01,  1.70959465e+00,
        -5.92373012e-01, -5.92373012e-01, -1.05276654e+00,
        -1.31979479e-01,  7.88807586e-01,  9.82172869e-02,
        -1.31979479e-01,  9.82172869e-02,  9.82172869e-02,
         9.82172869e-02, -8.22569778e-01,  3.28414053e-01,
         5.58610819e-01, -1.31979479e-01, -1.28296331e+00,
        -1.31979479e-01,  7.88807586e-01, -1.31979479e-01],
       [-1.34022653e+00, -1.34022653e+00, -1.39706395e+00,
        -1.28338910e+00, -1.34022653e+00, -1.16971425e+00,
        -1.34022653e+00, -1.28338910e+00, -1.34022653e+00,
        -1.28338910e+00, -1.28338910e+00, -1.22655167e+00,
        -1.34022653e+00, -1.51073881e+00, -1.45390138e+00,
        -1.28338910e+00, -1.39706395e+00, -1.34022653e+00,
        -1.16971425e+00, -1.28338910e+00, -1.16971425e+00,
        -1.28338910e+00, -1.56757623e+00, -1.16971425e+00,
        -1.05603939e+00, -1.22655167e+00, -1.22655167e+00,
        -1.28338910e+00, -1.34022653e+00, -1.22655167e+00,
        -1.22655167e+00, -1.28338910e+00, -1.28338910e+00,
        -1.34022653e+00, -1.28338910e+00, -1.45390138e+00,
        -1.39706395e+00, -1.34022653e+00, -1.39706395e+00,
        -1.28338910e+00, -1.39706395e+00, -1.39706395e+00,
        -1.39706395e+00, -1.22655167e+00, -1.05603939e+00,
        -1.34022653e+00, -1.22655167e+00, -1.34022653e+00,
        -1.28338910e+00, -1.34022653e+00,  5.35408562e-01,
         4.21733708e-01,  6.49083415e-01,  1.37546573e-01,
         4.78571135e-01,  4.21733708e-01,  5.35408562e-01,
        -2.60315415e-01,  4.78571135e-01,  8.07091462e-02,
        -1.46640561e-01,  2.51221427e-01,  1.37546573e-01,
         5.35408562e-01, -8.98031345e-02,  3.64896281e-01,
         4.21733708e-01,  1.94384000e-01,  4.21733708e-01,
         8.07091462e-02,  5.92245988e-01,  1.37546573e-01,
         6.49083415e-01,  5.35408562e-01,  3.08058854e-01,
         3.64896281e-01,  5.92245988e-01,  7.05920842e-01,
         4.21733708e-01, -1.46640561e-01,  2.38717193e-02,
        -3.29657076e-02,  8.07091462e-02,  7.62758269e-01,
         4.21733708e-01,  4.21733708e-01,  5.35408562e-01,
         3.64896281e-01,  1.94384000e-01,  1.37546573e-01,
         3.64896281e-01,  4.78571135e-01,  1.37546573e-01,
        -2.60315415e-01,  2.51221427e-01,  2.51221427e-01,
         2.51221427e-01,  3.08058854e-01, -4.30827696e-01,
         1.94384000e-01,  1.27429511e+00,  7.62758269e-01,
         1.21745768e+00,  1.04694540e+00,  1.16062026e+00,
         1.61531967e+00,  4.21733708e-01,  1.44480739e+00,
         1.16062026e+00,  1.33113254e+00,  7.62758269e-01,
         8.76433123e-01,  9.90107977e-01,  7.05920842e-01,
         7.62758269e-01,  8.76433123e-01,  9.90107977e-01,
         1.67215710e+00,  1.78583195e+00,  7.05920842e-01,
         1.10378283e+00,  6.49083415e-01,  1.67215710e+00,
         6.49083415e-01,  1.10378283e+00,  1.27429511e+00,
         5.92245988e-01,  6.49083415e-01,  1.04694540e+00,
         1.16062026e+00,  1.33113254e+00,  1.50164482e+00,
         1.04694540e+00,  7.62758269e-01,  1.04694540e+00,
         1.33113254e+00,  1.04694540e+00,  9.90107977e-01,
         5.92245988e-01,  9.33270550e-01,  1.04694540e+00,
         7.62758269e-01,  7.62758269e-01,  1.21745768e+00,
         1.10378283e+00,  8.19595696e-01,  7.05920842e-01,
         8.19595696e-01,  9.33270550e-01,  7.62758269e-01],
       [-1.31544430e+00, -1.31544430e+00, -1.31544430e+00,
        -1.31544430e+00, -1.31544430e+00, -1.05217993e+00,
        -1.18381211e+00, -1.31544430e+00, -1.31544430e+00,
        -1.44707648e+00, -1.31544430e+00, -1.31544430e+00,
        -1.44707648e+00, -1.44707648e+00, -1.31544430e+00,
        -1.05217993e+00, -1.05217993e+00, -1.18381211e+00,
        -1.18381211e+00, -1.18381211e+00, -1.31544430e+00,
        -1.05217993e+00, -1.31544430e+00, -9.20547742e-01,
        -1.31544430e+00, -1.31544430e+00, -1.05217993e+00,
        -1.31544430e+00, -1.31544430e+00, -1.31544430e+00,
        -1.31544430e+00, -1.05217993e+00, -1.44707648e+00,
        -1.31544430e+00, -1.31544430e+00, -1.31544430e+00,
        -1.31544430e+00, -1.44707648e+00, -1.31544430e+00,
        -1.31544430e+00, -1.18381211e+00, -1.18381211e+00,
        -1.31544430e+00, -7.88915558e-01, -1.05217993e+00,
        -1.18381211e+00, -1.31544430e+00, -1.31544430e+00,
        -1.31544430e+00, -1.31544430e+00,  2.64141916e-01,
         3.95774101e-01,  3.95774101e-01,  1.32509732e-01,
         3.95774101e-01,  1.32509732e-01,  5.27406285e-01,
        -2.62386821e-01,  1.32509732e-01,  2.64141916e-01,
        -2.62386821e-01,  3.95774101e-01, -2.62386821e-01,
         2.64141916e-01,  1.32509732e-01,  2.64141916e-01,
         3.95774101e-01, -2.62386821e-01,  3.95774101e-01,
        -1.30754636e-01,  7.90670654e-01,  1.32509732e-01,
         3.95774101e-01,  8.77547895e-04,  1.32509732e-01,
         2.64141916e-01,  2.64141916e-01,  6.59038469e-01,
         3.95774101e-01, -2.62386821e-01, -1.30754636e-01,
        -2.62386821e-01,  8.77547895e-04,  5.27406285e-01,
         3.95774101e-01,  5.27406285e-01,  3.95774101e-01,
         1.32509732e-01,  1.32509732e-01,  1.32509732e-01,
         8.77547895e-04,  2.64141916e-01,  8.77547895e-04,
        -2.62386821e-01,  1.32509732e-01,  8.77547895e-04,
         1.32509732e-01,  1.32509732e-01, -1.30754636e-01,
         1.32509732e-01,  1.71209594e+00,  9.22302838e-01,
         1.18556721e+00,  7.90670654e-01,  1.31719939e+00,
         1.18556721e+00,  6.59038469e-01,  7.90670654e-01,
         7.90670654e-01,  1.71209594e+00,  1.05393502e+00,
         9.22302838e-01,  1.18556721e+00,  1.05393502e+00,
         1.58046376e+00,  1.44883158e+00,  7.90670654e-01,
         1.31719939e+00,  1.44883158e+00,  3.95774101e-01,
         1.44883158e+00,  1.05393502e+00,  1.05393502e+00,
         7.90670654e-01,  1.18556721e+00,  7.90670654e-01,
         7.90670654e-01,  7.90670654e-01,  1.18556721e+00,
         5.27406285e-01,  9.22302838e-01,  1.05393502e+00,
         1.31719939e+00,  3.95774101e-01,  2.64141916e-01,
         1.44883158e+00,  1.58046376e+00,  7.90670654e-01,
         7.90670654e-01,  1.18556721e+00,  1.58046376e+00,
         1.44883158e+00,  9.22302838e-01,  1.44883158e+00,
         1.71209594e+00,  1.44883158e+00,  9.22302838e-01,
         1.05393502e+00,  1.44883158e+00,  7.90670654e-01]])

In [69]:
c.reshape(3,50,4)

array([[[-9.00681170e-01, -1.14301691e+00, -1.38535265e+00,
         -1.50652052e+00],
        [-1.02184904e+00, -5.37177559e-01, -1.50652052e+00,
         -1.02184904e+00],
        [-1.74885626e+00, -1.14301691e+00, -5.37177559e-01,
         -1.26418478e+00],
        [-1.26418478e+00, -1.87002413e+00, -5.25060772e-02,
         -1.73673948e-01],
        [-5.37177559e-01, -9.00681170e-01, -1.73673948e-01,
         -9.00681170e-01],
        [-5.37177559e-01, -9.00681170e-01, -1.50652052e+00,
         -9.00681170e-01],
        [-1.26418478e+00, -1.02184904e+00, -1.02184904e+00,
         -7.79513300e-01],
        [-7.79513300e-01, -1.38535265e+00, -1.26418478e+00,
         -5.37177559e-01],
        [-7.79513300e-01, -4.16009689e-01, -1.14301691e+00,
         -1.02184904e+00],
        [-4.16009689e-01, -1.14301691e+00, -1.74885626e+00,
         -9.00681170e-01],
        [-1.02184904e+00, -1.62768839e+00, -1.74885626e+00,
         -1.02184904e+00],
        [-9.00681170e-01, -1.26418478e+00, -9.00681170e-01,
         -1.50652052e+00],
        [-6.58345429e-01, -1.02184904e+00,  1.40150837e+00,
          6.74501145e-01],
        [ 1.28034050e+00, -4.16009689e-01,  7.95669016e-01,
         -1.73673948e-01],
        [ 5.53333275e-01, -1.14301691e+00,  9.16836886e-01,
         -7.79513300e-01],
        [-1.02184904e+00,  6.86617933e-02,  1.89829664e-01,
          3.10997534e-01],
        [-2.94841818e-01,  1.03800476e+00, -2.94841818e-01,
         -5.25060772e-02],
        [ 4.32165405e-01, -2.94841818e-01,  6.86617933e-02,
          3.10997534e-01],
        [ 5.53333275e-01,  3.10997534e-01,  6.74501145e-01,
          9.16836886e-01],
        [ 1.15917263e+00,  1.03800476e+00,  1.89829664e-01,
         -1.73673948e-01],
        [-4.16009689e-01, -4.16009689e-01, -5.25060772e-02,
          1.89829664e-01],
        [-5.37177559e-01,  1.89829664e-01,  1.03800476e+00,
          5.53333275e-01],
        [-2.94841818e-01, -4.16009689e-01, -4.16009689e-01,
          3.10997534e-01],
        [-5.25060772e-02, -1.02184904e+00, -2.94841818e-01,
         -1.73673948e-01],
        [-1.73673948e-01,  4.32165405e-01, -9.00681170e-01,
         -1.73673948e-01],
        [ 5.53333275e-01, -5.25060772e-02,  1.52267624e+00,
          5.53333275e-01],
        [ 7.95669016e-01,  2.12851559e+00, -1.14301691e+00,
          1.76501198e+00],
        [ 1.03800476e+00,  1.64384411e+00,  7.95669016e-01,
          6.74501145e-01],
        [ 1.15917263e+00, -1.73673948e-01, -5.25060772e-02,
          6.74501145e-01],
        [ 7.95669016e-01,  2.24968346e+00,  2.24968346e+00,
          1.89829664e-01],
        [ 1.28034050e+00, -2.94841818e-01,  2.24968346e+00,
          5.53333275e-01],
        [ 1.03800476e+00,  1.64384411e+00,  4.32165405e-01,
          3.10997534e-01],
        [ 6.74501145e-01,  1.64384411e+00,  1.88617985e+00,
          2.49201920e+00],
        [ 6.74501145e-01,  5.53333275e-01,  3.10997534e-01,
          2.24968346e+00],
        [ 5.53333275e-01,  6.74501145e-01,  1.89829664e-01,
          1.28034050e+00],
        [ 1.03800476e+00,  1.28034050e+00, -5.25060772e-02,
          1.15917263e+00],
        [ 1.03800476e+00,  1.03800476e+00,  5.53333275e-01,
          7.95669016e-01],
        [ 4.32165405e-01,  6.86617933e-02,  1.01900435e+00,
         -1.31979479e-01],
        [ 3.28414053e-01,  9.82172869e-02,  1.24920112e+00,
          1.93979142e+00],
        [ 7.88807586e-01,  7.88807586e-01, -3.62176246e-01,
          9.82172869e-02],
        [ 1.47939788e+00,  7.88807586e-01, -1.31979479e-01,
         -1.31979479e-01],
        [ 2.16998818e+00,  3.09077525e+00,  1.93979142e+00,
          1.01900435e+00],
        [ 1.70959465e+00,  1.70959465e+00,  7.88807586e-01,
          1.47939788e+00],
        [ 1.24920112e+00,  5.58610819e-01,  7.88807586e-01,
         -1.31979479e-01],
        [ 7.88807586e-01,  1.01900435e+00,  7.88807586e-01,
          3.28414053e-01],
        [ 9.82172869e-02,  7.88807586e-01,  2.40018495e+00,
          2.63038172e+00],
        [ 9.82172869e-02,  3.28414053e-01,  1.01900435e+00,
          1.24920112e+00],
        [-1.31979479e-01,  7.88807586e-01,  1.01900435e+00,
         -1.74335684e+00],
        [ 3.28414053e-01,  1.01900435e+00,  1.70959465e+00,
         -1.31979479e-01],
        [ 1.70959465e+00,  3.28414053e-01,  1.47939788e+00,
          5.58610819e-01]],

       [[ 3.28414053e-01,  3.28414053e-01,  9.82172869e-02,
         -1.74335684e+00],
        [-5.92373012e-01, -5.92373012e-01,  5.58610819e-01,
         -1.51316008e+00],
        [-3.62176246e-01, -8.22569778e-01, -2.43394714e+00,
         -1.31979479e-01],
        [-1.97355361e+00, -3.62176246e-01, -3.62176246e-01,
          9.82172869e-02],
        [-1.31979479e-01, -8.22569778e-01, -1.97355361e+00,
         -1.28296331e+00],
        [ 3.28414053e-01, -5.92373012e-01, -1.28296331e+00,
         -5.92373012e-01],
        [-3.62176246e-01, -1.31979479e-01, -5.92373012e-01,
         -1.31979479e-01],
        [-3.62176246e-01, -1.05276654e+00, -1.51316008e+00,
         -1.51316008e+00],
        [-8.22569778e-01, -8.22569778e-01, -1.31979479e-01,
          7.88807586e-01],
        [ 9.82172869e-02, -1.74335684e+00, -1.31979479e-01,
         -1.28296331e+00],
        [-1.05276654e+00, -1.31979479e-01, -1.05276654e+00,
         -1.74335684e+00],
        [-8.22569778e-01, -1.31979479e-01, -3.62176246e-01,
         -3.62176246e-01],
        [-1.28296331e+00, -5.92373012e-01,  5.58610819e-01,
         -8.22569778e-01],
        [-1.31979479e-01, -3.62176246e-01, -1.31979479e-01,
         -1.31979479e-01],
        [-1.28296331e+00, -3.62176246e-01, -1.28296331e+00,
          1.24920112e+00],
        [ 3.28414053e-01, -8.22569778e-01, -1.31979479e-01,
         -1.28296331e+00],
        [-5.92373012e-01,  3.28414053e-01, -1.31979479e-01,
          1.70959465e+00],
        [-1.05276654e+00, -1.97355361e+00,  3.28414053e-01,
         -5.92373012e-01],
        [-5.92373012e-01, -8.22569778e-01,  5.58610819e-01,
          3.28414053e-01],
        [-5.92373012e-01, -1.31979479e-01, -5.92373012e-01,
         -1.31979479e-01],
        [-5.92373012e-01,  1.70959465e+00, -5.92373012e-01,
         -5.92373012e-01],
        [-1.05276654e+00, -1.31979479e-01,  7.88807586e-01,
          9.82172869e-02],
        [-1.31979479e-01,  9.82172869e-02,  9.82172869e-02,
          9.82172869e-02],
        [-8.22569778e-01,  3.28414053e-01,  5.58610819e-01,
         -1.31979479e-01],
        [-1.28296331e+00, -1.31979479e-01,  7.88807586e-01,
         -1.31979479e-01],
        [-1.34022653e+00, -1.34022653e+00, -1.39706395e+00,
         -1.28338910e+00],
        [-1.34022653e+00, -1.16971425e+00, -1.34022653e+00,
         -1.28338910e+00],
        [-1.34022653e+00, -1.28338910e+00, -1.28338910e+00,
         -1.22655167e+00],
        [-1.34022653e+00, -1.51073881e+00, -1.45390138e+00,
         -1.28338910e+00],
        [-1.39706395e+00, -1.34022653e+00, -1.16971425e+00,
         -1.28338910e+00],
        [-1.16971425e+00, -1.28338910e+00, -1.56757623e+00,
         -1.16971425e+00],
        [-1.05603939e+00, -1.22655167e+00, -1.22655167e+00,
         -1.28338910e+00],
        [-1.34022653e+00, -1.22655167e+00, -1.22655167e+00,
         -1.28338910e+00],
        [-1.28338910e+00, -1.34022653e+00, -1.28338910e+00,
         -1.45390138e+00],
        [-1.39706395e+00, -1.34022653e+00, -1.39706395e+00,
         -1.28338910e+00],
        [-1.39706395e+00, -1.39706395e+00, -1.39706395e+00,
         -1.22655167e+00],
        [-1.05603939e+00, -1.34022653e+00, -1.22655167e+00,
         -1.34022653e+00],
        [-1.28338910e+00, -1.34022653e+00,  5.35408562e-01,
          4.21733708e-01],
        [ 6.49083415e-01,  1.37546573e-01,  4.78571135e-01,
          4.21733708e-01],
        [ 5.35408562e-01, -2.60315415e-01,  4.78571135e-01,
          8.07091462e-02],
        [-1.46640561e-01,  2.51221427e-01,  1.37546573e-01,
          5.35408562e-01],
        [-8.98031345e-02,  3.64896281e-01,  4.21733708e-01,
          1.94384000e-01],
        [ 4.21733708e-01,  8.07091462e-02,  5.92245988e-01,
          1.37546573e-01],
        [ 6.49083415e-01,  5.35408562e-01,  3.08058854e-01,
          3.64896281e-01],
        [ 5.92245988e-01,  7.05920842e-01,  4.21733708e-01,
         -1.46640561e-01],
        [ 2.38717193e-02, -3.29657076e-02,  8.07091462e-02,
          7.62758269e-01],
        [ 4.21733708e-01,  4.21733708e-01,  5.35408562e-01,
          3.64896281e-01],
        [ 1.94384000e-01,  1.37546573e-01,  3.64896281e-01,
          4.78571135e-01],
        [ 1.37546573e-01, -2.60315415e-01,  2.51221427e-01,
          2.51221427e-01],
        [ 2.51221427e-01,  3.08058854e-01, -4.30827696e-01,
          1.94384000e-01]],

       [[ 1.27429511e+00,  7.62758269e-01,  1.21745768e+00,
          1.04694540e+00],
        [ 1.16062026e+00,  1.61531967e+00,  4.21733708e-01,
          1.44480739e+00],
        [ 1.16062026e+00,  1.33113254e+00,  7.62758269e-01,
          8.76433123e-01],
        [ 9.90107977e-01,  7.05920842e-01,  7.62758269e-01,
          8.76433123e-01],
        [ 9.90107977e-01,  1.67215710e+00,  1.78583195e+00,
          7.05920842e-01],
        [ 1.10378283e+00,  6.49083415e-01,  1.67215710e+00,
          6.49083415e-01],
        [ 1.10378283e+00,  1.27429511e+00,  5.92245988e-01,
          6.49083415e-01],
        [ 1.04694540e+00,  1.16062026e+00,  1.33113254e+00,
          1.50164482e+00],
        [ 1.04694540e+00,  7.62758269e-01,  1.04694540e+00,
          1.33113254e+00],
        [ 1.04694540e+00,  9.90107977e-01,  5.92245988e-01,
          9.33270550e-01],
        [ 1.04694540e+00,  7.62758269e-01,  7.62758269e-01,
          1.21745768e+00],
        [ 1.10378283e+00,  8.19595696e-01,  7.05920842e-01,
          8.19595696e-01],
        [ 9.33270550e-01,  7.62758269e-01, -1.31544430e+00,
         -1.31544430e+00],
        [-1.31544430e+00, -1.31544430e+00, -1.31544430e+00,
         -1.05217993e+00],
        [-1.18381211e+00, -1.31544430e+00, -1.31544430e+00,
         -1.44707648e+00],
        [-1.31544430e+00, -1.31544430e+00, -1.44707648e+00,
         -1.44707648e+00],
        [-1.31544430e+00, -1.05217993e+00, -1.05217993e+00,
         -1.18381211e+00],
        [-1.18381211e+00, -1.18381211e+00, -1.31544430e+00,
         -1.05217993e+00],
        [-1.31544430e+00, -9.20547742e-01, -1.31544430e+00,
         -1.31544430e+00],
        [-1.05217993e+00, -1.31544430e+00, -1.31544430e+00,
         -1.31544430e+00],
        [-1.31544430e+00, -1.05217993e+00, -1.44707648e+00,
         -1.31544430e+00],
        [-1.31544430e+00, -1.31544430e+00, -1.31544430e+00,
         -1.44707648e+00],
        [-1.31544430e+00, -1.31544430e+00, -1.18381211e+00,
         -1.18381211e+00],
        [-1.31544430e+00, -7.88915558e-01, -1.05217993e+00,
         -1.18381211e+00],
        [-1.31544430e+00, -1.31544430e+00, -1.31544430e+00,
         -1.31544430e+00],
        [ 2.64141916e-01,  3.95774101e-01,  3.95774101e-01,
          1.32509732e-01],
        [ 3.95774101e-01,  1.32509732e-01,  5.27406285e-01,
         -2.62386821e-01],
        [ 1.32509732e-01,  2.64141916e-01, -2.62386821e-01,
          3.95774101e-01],
        [-2.62386821e-01,  2.64141916e-01,  1.32509732e-01,
          2.64141916e-01],
        [ 3.95774101e-01, -2.62386821e-01,  3.95774101e-01,
         -1.30754636e-01],
        [ 7.90670654e-01,  1.32509732e-01,  3.95774101e-01,
          8.77547895e-04],
        [ 1.32509732e-01,  2.64141916e-01,  2.64141916e-01,
          6.59038469e-01],
        [ 3.95774101e-01, -2.62386821e-01, -1.30754636e-01,
         -2.62386821e-01],
        [ 8.77547895e-04,  5.27406285e-01,  3.95774101e-01,
          5.27406285e-01],
        [ 3.95774101e-01,  1.32509732e-01,  1.32509732e-01,
          1.32509732e-01],
        [ 8.77547895e-04,  2.64141916e-01,  8.77547895e-04,
         -2.62386821e-01],
        [ 1.32509732e-01,  8.77547895e-04,  1.32509732e-01,
          1.32509732e-01],
        [-1.30754636e-01,  1.32509732e-01,  1.71209594e+00,
          9.22302838e-01],
        [ 1.18556721e+00,  7.90670654e-01,  1.31719939e+00,
          1.18556721e+00],
        [ 6.59038469e-01,  7.90670654e-01,  7.90670654e-01,
          1.71209594e+00],
        [ 1.05393502e+00,  9.22302838e-01,  1.18556721e+00,
          1.05393502e+00],
        [ 1.58046376e+00,  1.44883158e+00,  7.90670654e-01,
          1.31719939e+00],
        [ 1.44883158e+00,  3.95774101e-01,  1.44883158e+00,
          1.05393502e+00],
        [ 1.05393502e+00,  7.90670654e-01,  1.18556721e+00,
          7.90670654e-01],
        [ 7.90670654e-01,  7.90670654e-01,  1.18556721e+00,
          5.27406285e-01],
        [ 9.22302838e-01,  1.05393502e+00,  1.31719939e+00,
          3.95774101e-01],
        [ 2.64141916e-01,  1.44883158e+00,  1.58046376e+00,
          7.90670654e-01],
        [ 7.90670654e-01,  1.18556721e+00,  1.58046376e+00,
          1.44883158e+00],
        [ 9.22302838e-01,  1.44883158e+00,  1.71209594e+00,
          1.44883158e+00],
        [ 9.22302838e-01,  1.05393502e+00,  1.44883158e+00,
          7.90670654e-01]]])

In [109]:
iris=sns.load_dataset('iris')
iris.loc[:,'size_category']=pd.cut(iris.loc[:,'petal_length'],bins=[0,2.5,5,max(iris.loc[:,'petal_length'])],labels=['small','medium','large'])
iris.head(5)

   sepal_length  sepal_width  petal_length  petal_width species size_category
0           5.1          3.5           1.4          0.2  setosa         small
1           4.9          3.0           1.4          0.2  setosa         small
2           4.7          3.2           1.3          0.2  setosa         small
3           4.6          3.1           1.5          0.2  setosa         small
4           5.0          3.6           1.4          0.2  setosa         small

In [92]:
iris.iloc[:,0:5].groupby('species').agg(['mean','min','max'])

           sepal_length           sepal_width           petal_length       \
                   mean  min  max        mean  min  max         mean  min
species
setosa            5.006  4.3  5.8       3.428  2.3  4.4        1.462  1.0
versicolor        5.936  4.9  7.0       2.770  2.0  3.4        4.260  3.0
virginica         6.588  4.9  7.9       2.974  2.2  3.8        5.552  4.5

                petal_width
            max        mean  min  max
species
setosa      1.9       0.246  0.1  0.6
versicolor  5.1       1.326  1.0  1.8
virginica   6.9       2.026  1.4  2.5

In [97]:
iris.loc[:,'sepal_ratio']=iris.loc[:,'sepal_length']/iris.loc[:,'sepal_width']
iris.loc[:,'petal_ratio']=iris.loc[:,'petal_length']/iris.loc[:,'petal_width']
iris.iloc[:,-2:].corr()

             sepal_ratio  petal_ratio
sepal_ratio     1.000000    -0.611992
petal_ratio    -0.611992     1.000000

In [111]:
pd.pivot_table(iris,index='species',columns='size_category',values='petal_length',aggfunc='count')

C:\Users\dell\AppData\Local\Temp\ipykernel_33056\557236075.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(iris,index='species',columns='size_category',values='petal_length',aggfunc='count')

size_category  small  medium  large
species
setosa            50       0      0
versicolor         0      49      1
virginica          0       9     41

In [9]:
import numpy as np
import pandas as pd
data = np.array([
    ["Alice", 25, 90],
    ["Bob", 35, 85],
    ["Charlie", 28, 95],
    ["David", 45, 80],
    ["Eve", 22, 92]
])
df = pd.DataFrame(
    data,
    columns=['name', 'age', 'score'],  # 列名（3个，与数据列数匹配）
    index=np.arange(0, 5, 1)  # 索引0-4（5个，与数据行数匹配，修正你的4→5）
)
df['age']=df['age'].astype(int)
df['score']=df['score'].astype(int)

def dis(x):
    if x > 50:
        return '老年'
    elif x < 30:
        return '青年'
    else:
        return '中年'


# 3. map函数应用+深拷贝（修正：函数调用，统一引号）
age_new = df['age'].map(dis).copy()  # 正确，保留

age_new

0    青年
1    中年
2    青年
3    中年
4    青年
Name: age, dtype: object