In [1]:
import pandas as pd
import numpy as np

# hierarchical index

In [25]:
df=pd.DataFrame({
    'group':['G1','G2','G1','G2'],
    'subgroup':['a','b','c','d'],
    'value1':[1,2,3,4],
    'value2':[5,6,7,8]})
df

  group subgroup  value1  value2
0    G1        a       1       5
1    G2        b       2       6
2    G1        c       3       7
3    G2        d       4       8

In [26]:
df.set_index(['group'])

      subgroup  value1  value2
group
G1           a       1       5
G2           b       2       6
G1           c       3       7
G2           d       4       8

In [27]:
df=df.set_index(['group','subgroup'])
print(df.loc['G1'])

          value1  value2
subgroup
a              1       5
c              3       7

In [36]:
#from tuples
index=pd.MultiIndex.from_tuples([
    ('G1','a'),
    ('G1','b'),
    ('G2','a'),
    ('G2','b'),],names=['group','subgroup'])

In [37]:
np.random.seed(2323)
data=pd.DataFrame(np.random.randn(4,2),index=index,columns=['v1','v2'])
data

                      v1        v2
group subgroup
G1    a         0.345380  2.108230
      b        -0.214280  0.119541
G2    a         1.372511 -0.282634
      b        -1.146024 -1.363673

In [40]:
#from array
l1=['g1','g1','g2','g2']
l2=['a','b','c','d']

index=pd.MultiIndex.from_arrays([l1,l2],names=['group','subgroup'])
np.random.seed(2323)
data=pd.DataFrame(np.random.randn(4,2),index=index,columns=['v1','v2'])
data

                      v1        v2
group subgroup
g1    a         0.345380  2.108230
      b        -0.214280  0.119541
g2    c         1.372511 -0.282634
      d        -1.146024 -1.363673

In [44]:
#remove index
df1=df.reset_index(level='group')
df1.loc['a']

group     G1
value1     1
value2     5
Name: a, dtype: object

In [54]:
df=pd.DataFrame({
    'group':['G1','G2','G1','G2'],
    'subgroup':['a','b','a','b'],
    'value1':[1,2,3,4],
    'value2':[5,6,7,8]})
gdf=df.groupby(['group','subgroup']).agg({'value1':'sum'})
print(gdf)

                value1
group subgroup
G1    a              4
G2    b              6

# long and vide data format

In [63]:
data={
    'student':['ali','siti'],
    'math':[80,78],
    'science':[75,82],
    'english':[89,83]}
data_wide=pd.DataFrame(data)
print(data_wide)

  student  math  science  english
0     ali    80       75       89
1    siti    78       82       83

In [69]:
#wide to long
df=pd.melt(data_wide,id_vars=['student'],value_vars=['math','science','english'],var_name='subject',value_name='score')

In [65]:
#wide to long
data_wide.set_index(['student']).stack()

student
ali      math       80
         science    75
         english    89
siti     math       78
         science    82
         english    83
dtype: int64

In [73]:
#long to wide
df.set_index(['student','subject']).unstack()

          score
subject english math science
student
ali          89   80      75
siti         83   78      82

In [75]:
#long to wide
df.pivot(index='student',columns='subject',values='score')

subject  english  math  science
student
ali           89    80       75
siti          83    78       82

# merging

In [91]:
df1=pd.DataFrame({'key1':['a','b','c'],'value':[1,2,3]})
df2=pd.DataFrame({'key2':['a','b','c','d'],'value':[4,5,6,7]})
pd.merge(df1,df2,left_on='key1',right_on='key2',how='outer').drop('key2',axis=1)

  key1  value_x  value_y
0    a      1.0        4
1    b      2.0        5
2    c      3.0        6
3  NaN      NaN        7

In [93]:
df1=pd.DataFrame({'key1':['a','b','c'],'value':[1,2,3]})
df2=pd.DataFrame({'key2':['a','b','c','d'],'value':[4,5,6,7]})
df2=df2.rename(columns={'key2':'key1'})
pd.merge(df1,df2,on='key1',how='outer')

  key1  value_x  value_y
0    a      1.0        4
1    b      2.0        5
2    c      3.0        6
3    d      NaN        7

# concatenating

In [98]:
df1=pd.DataFrame({'a':[1,2],'b':[3,4]})
df2=pd.DataFrame({'a':[5,6],'b':[7,8]})
pd.concat([df1,df2],axis=1,join='outer')

   a  b  a  b
0  1  3  5  7
1  2  4  6  8

## exercise

In [116]:
data=pd.read_csv('clean.csv',skiprows=4,na_values=['-'])
data.columns=data.columns.str.lower()
data=data.drop('no',axis=1)
data=data.drop_duplicates()
data['name']=data['name'].str.strip()
data['dishwasher']=data['dishwasher'].str.replace(r'[^\w]','',regex=True)
data['dishwasher']=data['dishwasher'].str.lower()
data['no of mugs/plates']=data['no of mugs/plates'].str.replace(r'[^\d]','',regex=True)
data['sink']=data['sink table'].str.contains('sink|both')
data['table']=data['sink table'].str.contains('table|both')
data_clean=data[['name','sink','table','no of mugs/plates','dishwasher']]
data_clean

      name   sink  table no of mugs/plates dishwasher
0      Ali   True  False                 9         no
1    Johan   True   True                23        yes
2     Daus   True   True                 8        yes
3   George    NaN    NaN                 0        NaN
4   Amelia  False   True                10        yes
5    Ahmad   True   True                 6         no
7      Ava  False  False                 4         no
8    Harry   True  False                 3         no
9    Cindy   True   True                69        yes
10   Ariel  False   True                 2         no

In [173]:
df1=pd.read_csv('emp1.csv',skiprows=1)
df2=pd.read_csv('emp2.csv',skiprows=2)
print(df1)
print(df2)

      id  grade    status        type first name  last name  salary
0  10212     41    active   permanent        ali      smith    2200
1  10213     41    active   permanent       john        doe    2300
2  10214     44    active   permanent     sheryl  armstrong    3600
3  10215     42    active   permanent      haily     bailey    2500
4  10216     48    active    contract    jackson      green    5200
5  10217     54    active   permanent     martin     parker    5200
6  10218     41  inactive   contract        rose     taylor    2600
7  10219     52    active    contract     wilson       wood    6600
8  10220     42    active   permanent   mitchell        lee    2500
      id  grade    status        type            name  salary
0  10221     41    active   permanent  lawrence lloyd    2420
1  10222     41  inactive   permanent     james moore    2530
2  10223     44    active   permanent   amelia phills    3960
3  10224     42    active   permanent     sally price    2750
4  10225     48    active    contract   amanda taylor    5720
5  10226     54    active   permanent    robert scort    5720
6  10227     41    active   contract      rose taylor    2860
7  10228     52    active    contract     thomas will    7260
8  10229     42    active   permanent    nicole white    2750

In [174]:
for i in df1.select_dtypes(include=['object']).columns:
    df1[i]=df1[i].str.strip()
for i in df2.select_dtypes(include=['object']).columns:
    df2[i]=df2[i].str.strip()
print(df1)
print(df2)

      id  grade    status       type first name  last name  salary
0  10212     41    active  permanent        ali      smith    2200
1  10213     41    active  permanent       john        doe    2300
2  10214     44    active  permanent     sheryl  armstrong    3600
3  10215     42    active  permanent      haily     bailey    2500
4  10216     48    active   contract    jackson      green    5200
5  10217     54    active  permanent     martin     parker    5200
6  10218     41  inactive   contract       rose     taylor    2600
7  10219     52    active   contract     wilson       wood    6600
8  10220     42    active  permanent   mitchell        lee    2500
      id  grade    status       type            name  salary
0  10221     41    active  permanent  lawrence lloyd    2420
1  10222     41  inactive  permanent     james moore    2530
2  10223     44    active  permanent   amelia phills    3960
3  10224     42    active  permanent     sally price    2750
4  10225     48    active   contract   amanda taylor    5720
5  10226     54    active  permanent    robert scort    5720
6  10227     41    active   contract     rose taylor    2860
7  10228     52    active   contract     thomas will    7260
8  10229     42    active  permanent    nicole white    2750

In [175]:
df1=df1.rename(columns={'salary':'salary (MYR)'})
df2=df2.rename(columns={'salary':'salary (USD)'})
print(df1)
print(df2)

      id  grade    status       type first name  last name  salary (MYR)
0  10212     41    active  permanent        ali      smith          2200
1  10213     41    active  permanent       john        doe          2300
2  10214     44    active  permanent     sheryl  armstrong          3600
3  10215     42    active  permanent      haily     bailey          2500
4  10216     48    active   contract    jackson      green          5200
5  10217     54    active  permanent     martin     parker          5200
6  10218     41  inactive   contract       rose     taylor          2600
7  10219     52    active   contract     wilson       wood          6600
8  10220     42    active  permanent   mitchell        lee          2500
      id  grade    status       type            name  salary (USD)
0  10221     41    active  permanent  lawrence lloyd          2420
1  10222     41  inactive  permanent     james moore          2530
2  10223     44    active  permanent   amelia phills          3960
3  10224     42    active  permanent     sally price          2750
4  10225     48    active   contract   amanda taylor          5720
5  10226     54    active  permanent    robert scort          5720
6  10227     41    active   contract     rose taylor          2860
7  10228     52    active   contract     thomas will          7260
8  10229     42    active  permanent    nicole white          2750

In [176]:
df1['name']=df1['first name']+df1['last name']
df1

,id,grade,status,type,first name,last name,salary (MYR),name
0,10212,41,active,permanent,ali,smith,2200,alismith
1,10213,41,active,permanent,john,doe,2300,johndoe
2,10214,44,active,permanent,sheryl,armstrong,3600,sherylarmstrong
3,10215,42,active,permanent,haily,bailey,2500,hailybailey
4,10216,48,active,contract,jackson,green,5200,jacksongreen
5,10217,54,active,permanent,martin,parker,5200,martinparker
6,10218,41,inactive,contract,rose,taylor,2600,rosetaylor
7,10219,52,active,contract,wilson,wood,6600,wilsonwood
8,10220,42,active,permanent,mitchell,lee,2500,mitchelllee

In [177]:
df=pd.merge(df1,df2,on='id',how='outer')

In [178]:
df=df.loc[(df['status_x']=='active')|(df['status_y']=='active')]
df

,id,grade_x,status_x,type_x,first name,last name,salary (MYR),name_x,grade_y,status_y,type_y,name_y,salary (USD)
0,10212,41.0,active,permanent,ali,smith,2200.0,alismith,NaN,NaN,NaN,NaN,NaN
1,10213,41.0,active,permanent,john,doe,2300.0,johndoe,NaN,NaN,NaN,NaN,NaN
2,10214,44.0,active,permanent,sheryl,armstrong,3600.0,sherylarmstrong,NaN,NaN,NaN,NaN,NaN
3,10215,42.0,active,permanent,haily,bailey,2500.0,hailybailey,NaN,NaN,NaN,NaN,NaN
4,10216,48.0,active,contract,jackson,green,5200.0,jacksongreen,NaN,NaN,NaN,NaN,NaN
5,10217,54.0,active,permanent,martin,parker,5200.0,martinparker,NaN,NaN,NaN,NaN,NaN
7,10219,52.0,active,contract,wilson,wood,6600.0,wilsonwood,NaN,NaN,NaN,NaN,NaN
8,10220,42.0,active,permanent,mitchell,lee,2500.0,mitchelllee,NaN,NaN,NaN,NaN,NaN
9,10221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,active,permanent,lawrence lloyd,2420.0
11,10223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.0,active,permanent,amelia phills,3960.0
12,10224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0,active,permanent,sally price,2750.0
13,10225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,active,contract,amanda taylor,5720.0
14,10226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.0,active,permanent,robert scort,5720.0
15,10227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,active,contract,rose taylor,2860.0
16,10228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.0,active,contract,thomas will,7260.0
17,10229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0,active,permanent,nicole white,2750.0

In [179]:
df[['id','name_x','grade_x','status_x','type_x','name_y','grade_y','status_y','type_y','salary (MYR)','salary (USD)']]

,id,name_x,grade_x,status_x,type_x,name_y,grade_y,status_y,type_y,salary (MYR),salary (USD)
0,10212,alismith,41.0,active,permanent,NaN,NaN,NaN,NaN,2200.0,NaN
1,10213,johndoe,41.0,active,permanent,NaN,NaN,NaN,NaN,2300.0,NaN
2,10214,sherylarmstrong,44.0,active,permanent,NaN,NaN,NaN,NaN,3600.0,NaN
3,10215,hailybailey,42.0,active,permanent,NaN,NaN,NaN,NaN,2500.0,NaN
4,10216,jacksongreen,48.0,active,contract,NaN,NaN,NaN,NaN,5200.0,NaN
5,10217,martinparker,54.0,active,permanent,NaN,NaN,NaN,NaN,5200.0,NaN
7,10219,wilsonwood,52.0,active,contract,NaN,NaN,NaN,NaN,6600.0,NaN
8,10220,mitchelllee,42.0,active,permanent,NaN,NaN,NaN,NaN,2500.0,NaN
9,10221,NaN,NaN,NaN,NaN,lawrence lloyd,41.0,active,permanent,NaN,2420.0
11,10223,NaN,NaN,NaN,NaN,amelia phills,44.0,active,permanent,NaN,3960.0
12,10224,NaN,NaN,NaN,NaN,sally price,42.0,active,permanent,NaN,2750.0
13,10225,NaN,NaN,NaN,NaN,amanda taylor,48.0,active,contract,NaN,5720.0
14,10226,NaN,NaN,NaN,NaN,robert scort,54.0,active,permanent,NaN,5720.0
15,10227,NaN,NaN,NaN,NaN,rose taylor,41.0,active,contract,NaN,2860.0
16,10228,NaN,NaN,NaN,NaN,thomas will,52.0,active,contract,NaN,7260.0
17,10229,NaN,NaN,NaN,NaN,nicole white,42.0,active,permanent,NaN,2750.0

In [180]:
df.shape

(16, 13)

In [191]:
order=df.sort_values('salary (USD)',ascending=False)

In [192]:
print(order.iloc[3])

id                      10223
grade_x                   NaN
status_x                  NaN
type_x                    NaN
first name                NaN
last name                 NaN
salary (MYR)              NaN
name_x                    NaN
grade_y                  44.0
status_y               active
type_y              permanent
name_y          amelia phills
salary (USD)           3960.0
Name: 11, dtype: object