In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.3'

In [13]:
s=pd.Series([2,4,1,5,6,8,3,6,2])
s=s.astype('float64')
print(s.dtypes)

float64

# creat series

In [3]:
ls=[1,2,3,4,5,6]
se=pd.Series(ls)
print(se)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [16]:
arr=np.arange(9)
se=pd.Series(arr)
print(se)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
dtype: int64

In [5]:
dic={'a':1,'b':2}
se=pd.Series(dic)
print(se)

a    1
b    2
dtype: int64

In [7]:
se.size

2

In [9]:
se.dtype

dtype('int64')

In [11]:
se=se.astype('float64')
se.dtype

dtype('float64')

In [12]:
se.info

<bound method Series.info of a    1.0
b    2.0
dtype: float64>

In [20]:
print(se)
se.drop(0)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
dtype: int64

1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
dtype: int64

# creat dataframe

In [32]:
ls1=[1,2,3,4]
ls2=[2,3,4,5]
ls3=[3,4,5,6]
df=pd.DataFrame([ls1,ls2,ls3],columns=['A','B','C','D'],index=[1,2,3])
print(df)

   A  B  C  D
1  1  2  3  4
2  2  3  4  5
3  3  4  5  6

In [33]:
df=pd.DataFrame(np.array([ls1,ls2,ls3]),index=np.arange(1,4,1))
print(df)

   0  1  2  3
1  1  2  3  4
2  2  3  4  5
3  3  4  5  6

In [14]:
dic={'r1':[1,2,3],'r2':[4,5,6],'r3':[7,8,9]}
df=pd.DataFrame(dic)
print(df)
df.info()

   r1  r2  r3
0   1   4   7
1   2   5   8
2   3   6   9
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   r1      3 non-null      int64
 1   r2      3 non-null      int64
 2   r3      3 non-null      int64
dtypes: int64(3)
memory usage: 200.0 bytes

In [17]:
df['r1']=df['r1'].astype('float')
df.dtypes

r1    float64
r2      int64
r3      int64
dtype: object

In [11]:
df.drop(2,axis=0)

   r1  r2  r3
0   1   4   7
1   2   5   8

In [43]:
df.drop('r2',axis=1)

   r1  r3
0   1   7
1   2   8
2   3   9

### exercise1

In [69]:
np.random.seed(123)
gr=np.random.randint(60,100,size=(30,5))
su=['math','bio','physic','chemistry','english']

# collect averge grade per student, and find the best student
df=pd.DataFrame(gr,columns=su,index=np.arange(1,31,1))
df

    math  bio  physic  chemistry  english
1     62   88      94         98       77
2     79   82      93         92       69
3     92   92      85         79       74
4     96   92      76         64       63
5     62   80      99         62       80
6     67   95      88         98       93
7     81   90      87         94       93
8     72   63      65         60       71
9     94   70      82         73       78
10    96   75      87         90       66
11    86   76      66         74       99
12    71   67      61         97       85
13    80   72      78         77       61
14    87   82      63         63       71
15    81   85      99         94       63
16    71   63      90         66       69
17    83   74      98         79       66
18    72   87      98         77       70
19    95   95      61         76       65
20    82   75      85         60       95
21    89   61      79         64       90
22    67   89      98         61       72
23    63   67      98         84       66
24    73   88      80         96       92
25    84   73      68         74       66
26    61   90      66         70       72
27    72   85      67         73       61
28    74   83      93         63       77
29    84   83      65         93       97
30    62   78      95         78       87

In [84]:
df['avg']=np.mean(df,axis=1)
df

    math  bio  physic  chemistry  english   avg
1     62   88      94         98       77  83.8
2     79   82      93         92       69  83.0
3     92   92      85         79       74  84.4
4     96   92      76         64       63  78.2
5     62   80      99         62       80  76.6
6     67   95      88         98       93  88.2
7     81   90      87         94       93  89.0
8     72   63      65         60       71  66.2
9     94   70      82         73       78  79.4
10    96   75      87         90       66  82.8
11    86   76      66         74       99  80.2
12    71   67      61         97       85  76.2
13    80   72      78         77       61  73.6
14    87   82      63         63       71  73.2
15    81   85      99         94       63  84.4
16    71   63      90         66       69  71.8
17    83   74      98         79       66  80.0
18    72   87      98         77       70  80.8
19    95   95      61         76       65  78.4
20    82   75      85         60       95  79.4
21    89   61      79         64       90  76.6
22    67   89      98         61       72  77.4
23    63   67      98         84       66  75.6
24    73   88      80         96       92  85.8
25    84   73      68         74       66  73.0
26    61   90      66         70       72  71.8
27    72   85      67         73       61  71.6
28    74   83      93         63       77  78.0
29    84   83      65         93       97  84.4
30    62   78      95         78       87  80.0

In [89]:
np.max(df['avg'])

np.float64(89.0)

In [92]:
np.argmax(df['avg'])

np.int64(6)

### exercise2

In [70]:
stu=['ali','abu','sara']
gco=[80,75,65]
gra=['a','b','c']
df=pd.DataFrame(np.array([stu,gco,gra]).T,columns=['student','gcove','grade'],index=['s1','s2','s3'])
df

   student gcove grade
s1     ali    80     a
s2     abu    75     b
s3    sara    65     c

In [52]:
df.dtypes

student    object
gcove      object
grade      object
dtype: object

In [53]:
se=pd.Series(np.arange(10,51,10))
se

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [55]:
se[0]

np.int64(10)

In [56]:
df.iloc[0]

student    ali
gcove       80
grade        a
Name: 0, dtype: object

In [59]:
se>30

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [61]:
df[['student','grade']]

  student grade
0     ali     a
1     abu     b
2    sara     c

In [74]:
df.iloc[0]

student    ali
gcove       80
grade        a
Name: s1, dtype: object

In [75]:
df.loc['s2']

student    abu
gcove       75
grade        b
Name: s2, dtype: object

In [76]:
df.iloc[1,2]

'b'

In [82]:
df[df['gcove'].astype('float')>30]['gcove']

s1    80
s2    75
s3    65
Name: gcove, dtype: object

In [90]:
df.loc[df['gcove'].astype('float')>30,'grade']

s1    a
s2    b
s3    c
Name: grade, dtype: object

In [91]:
df.iloc[-2:]

   student gcove grade
s2     abu    75     b
s3    sara    65     c

In [92]:
df[:-2]

   student gcove grade
s1     ali    80     a

In [106]:
df2=pd.DataFrame({'A':[10,20,30],'B':[40,50,60]},index=['a','b','c'])
df1+df2

    A   B
a  11  47
b  22  58
c  33  69

In [103]:
s1=pd.Series([5,5],index=['A','B'])
df1+s1

   A   B
a  6   9
b  7  10
c  8  11

In [108]:
df1['A'].mean

<bound method Series.mean of a    1
b    2
c    3
Name: A, dtype: int64>

In [110]:
df1['A'].describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
Name: A, dtype: float64

In [111]:
s1=pd.Series([1,2,3,4,5])
np.sqrt(s1)

0    1.000000
1    1.414214
2    1.732051
3    2.000000
4    2.236068
dtype: float64

In [112]:
df1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'B':[7,8,9]},index=['a','b','c'])
np.sqrt(df1)

          A         B
a  1.000000  2.645751
b  1.414214  2.828427
c  1.732051  3.000000

# apply and map

In [113]:
s1.apply(np.sqrt)

0    1.000000
1    1.414214
2    1.732051
3    2.000000
4    2.236068
dtype: float64

In [115]:
s1.apply(np.sum,axis=0)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [121]:
df1.apply(np.sum,axis=1)

a     8
b    10
c    12
dtype: int64

In [125]:
df1.map(np.square)

   A   B
a  1  49
b  4  64
c  9  81

In [127]:
def mult(x):
    return np.sum(x)
df1.apply(mult,axis=0)

A     6
B    24
dtype: int64

# pivot table and cross tabulation

In [143]:
data={
    'city':['kl','kunming','kl','kunming','kl'],
    'category':['a','a','b','b','a'],
    'sales':[2323,5324,6453,6248,6456]}
df=pd.DataFrame(data)
df

      city category  sales
0       kl        a   2323
1  kunming        a   5324
2       kl        b   6453
3  kunming        b   6248
4       kl        a   6456

In [135]:
pd.pivot_table(df,values='sales',index='city',columns='category')

category       a       b
city
kl        2323.0  6453.0
kunming   5324.0  6248.0

In [136]:
pd.pivot_table(df,values='sales',index=['city','category'])

                   sales
city    category
kl      a         2323.0
        b         6453.0
kunming a         5324.0
        b         6248.0

In [137]:
pd.pivot_table(df,values='sales',index='city',aggfunc='sum')

         sales
city
kl        8776
kunming  11572

In [145]:
pd.crosstab(index=df['city'],columns=df['category'])

category  a  b
city
kl        2  1
kunming   1  1

# view and copy

In [148]:
df1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]},index=['a','b','c'])
view=df1['A']
view[0]=9999
print(df1)
print(view)

      A  B  C
a  9999  4  7
b     2  5  8
c     3  6  9
a    9999
b       2
c       3
Name: A, dtype: int64

C:\Users\dell\AppData\Local\Temp\ipykernel_27420\3996346894.py:3: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  view[0]=9999

In [150]:
df1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]},index=['a','b','c'])
view=df1['A'].copy()
view[0]=9999
print(df1)
print(view)

   A  B  C
a  1  4  7
b  2  5  8
c  3  6  9
a    9999
b       2
c       3
Name: A, dtype: int64

C:\Users\dell\AppData\Local\Temp\ipykernel_27420\3308454775.py:3: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  view[0]=9999

In [155]:
df1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]},index=['a','b','c'])
subset=df1[df1['A']>1].copy()
subset['B']=9999
print(df1)
print(subset)

   A  B  C
a  1  4  7
b  2  5  8
c  3  6  9
   A     B  C
b  2  9999  8
c  3  9999  9